### PR TITLE
#1239 AWS::Serverless::Api Tags are not visible in the API Gateway co…

### PR DESCRIPTION
**Pull request by lskrajny**
…nsole under "Configure Tags"

*Issue #, if available:*
#1239
*Description of changes:*
Done the changes as advised
*Description of how you validated changes:*
Tests were updated and make pr ran
*Checklist:*

- [x] Write/update tests
- [x] `make pr` passes
- [ ] Update documentation
- [x] Verify transformed template deploys and application functions as expected
- [ ] Add/update example to `examples/2016-10-31`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ShreyaGangishetty** [comment]
@lskrajny Thank you for contributing this. Could you please resolve merge conflicts and update the PR?

**Comment by keetonian** [comment]
In testing this feature, it seems like it works to add tags to an ApiGateway Stage resource but not to an ApiGateway RestApi resource. The template deploys fine, but the CLI does not return any tags on the RestApi resource.

The template configuration looks correct, however, in this PR. I think we can approve this then follow up with ApiGateway about why tags don't work on RestApi resources.

```yaml
---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ServerlessRestApiDeploymentb9a4f42ab9:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: ServerlessRestApi
      Description: 'RestApi deployment id: b9a4f42ab99dd8b0342de400beae778b6162cb0f'
      StageName: Stage
  MyFunction2:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Code:
        ZipFile: |
          def handler(event, context):
              print(event)
              return {'body': 'Hello World 2!', 'statusCode': 200}
      Role:
        Fn::GetAtt:
        - MyFunction2Role
        - Arn
      Runtime: python3.7
      Tags:
      - Value: SAM
        Key: lambda:createdBy
  ServerlessRestApiProdStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId:
        Ref: ServerlessRestApiDeploymentb9a4f42ab9
      RestApiId:
        Ref: ServerlessRestApi
      StageName: Prod
  MyFunction2Role:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
  MyFunction2ApiPermissionProd:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      Principal: apigateway.amazonaws.com
      FunctionName:
        Ref: MyFunction2
      SourceArn:
        Fn::Sub:
        - arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${__ApiId__}/${__Stage__}/GET/
        - __Stage__: "*"
          __ApiId__:
            Ref: ServerlessRestApi
  ServerlessRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Body:
        info:
          version: '1.0'
          title:
            Ref: AWS::StackName
        paths:
          "/":
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MyFunction2.Arn}/invocations
              responses: {}
        swagger: '2.0'
      Tags:
      - Value: SAM
        Key: lambda:createdBy
```

**Comment by keetonian** [comment]
Add in the docs that these tags will get applied to the RestApi resource
https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessapi

**Comment by keetonian** [comment]
It looks like this feature deploys, but doesn't actually work as intended. See https://github.com/awslabs/serverless-application-model/issues/1239#issuecomment-562763620 for full details.

Thank you for submitting this PR, and sorry for the back and forth for something that ultimately doesn't accomplish the end goal of adding tags to this resource.

**Pull request closed without merging**
