### PR TITLE
Add Access log and canary setting support to templates.

### PR DESCRIPTION
**Pull request by tryantwit**
*Issue #, if available:*
#612 
*Description of changes:*
Added samtranslator support for AccessLogSetting and CanarySetting to Api Gateway.
Translator tests updated.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jvanbrunschot-coolblue** [comment]
Can we release this :)

**Comment by brettstack** [comment]
#516

**Comment by anishsam** [comment]
Hi,

When will this be available? I see this documented in https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md, however when I tried with sam verify, it fails.

Error: [InvalidResourceException('ApiGwBookstoreApi', 'property AccessLogSetting not defined for resource of type AWS::Serverless::Api')] ('ApiGwBookstoreApi', 'property AccessLogSetting not defined for resource of type AWS::Serverless::Api')

**Comment by keetonian** [comment]
It will be available with the next release. It is merged into develop right now, we will prepare a release and merge it to master to make it available in SAM

**Comment by alanwill** [comment]
Any idea when this will happen? Not to be a nag but it's misleading that it's showing up in the documentation when it really isn't released yet and looks like it's been like that for at least a month already.

**Pull request merged**
