### PR TITLE
Prob: Cannot offer Lambdas that manage Route53 for customers.

### PR DESCRIPTION
**Pull request by tristanls**
*Issue #, if available:*
#588 

*Description of changes:*
Include Route53ChangeResourceRecordSetsPolicy.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by keetonian** [comment]
Hi! Thank you for submitting this pull request! It looks like the Travis build is failing because of an issue that was fixed on develop but has not yet made it to master. Could you please rebase and submit this PR to the `develop` branch?

Also, we would appreciate it if you could also add this new policy to our tests, like was done in https://github.com/awslabs/serverless-application-model/pull/586/files. Thank you for your contribution!

**Comment by tristanls** [comment]
Updated per your instructions... sorry about the large diffs... seems there are random spaces at ends of many lines.

**Comment by keetonian** [comment]
No worries! It looks like a lot of that needed to be cleaned anyways. We are reviewing your submission and will get back to you soon!

**Comment by brettstack** [comment]
@tristanls could you split this into 2 Policy Templates? From the docs https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/r53-api-permissions-ref.html,  `ChangeResourceRecordSets` can have a `Resource` of `arn:aws:route53:::hostedzone/hostedZoneId`, while the other 2 can have `*`

**Comment by jfuss** [comment]
Closing due to lack of response

**Pull request closed without merging**
