### PR TITLE
Tell PyPI long_description is Markdown

### LINKED ISSUE #609: Rendering on PyPI is broken
**Description:**
Rendering of the README on PyPI is broken because it expects RST by default and Markdown is being uploaded.

**Steps to reproduce the issue:**

1. Go to https://pypi.org/project/aws-sam-translator/

**Observed result:**

Raw markdown

**Expected result:**

Links and images working

### PR DESCRIPTION
**Pull request by adamchainz**
*Issue #, if available:* #609

*Description of changes:*

Fixes #609. This will apply from the next release.

Cf https://github.com/aws/aws-xray-sdk-python/pull/101

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by brettstack** [comment]
This is awesome! I didn't even know this was an option and I was dreading having to convert all our files to RST. I'll approve now but will wait for you to respond before merging in case you want to sign up for Hacktoberfest like James mentioned

**Comment by brettstack** [comment]
Changed base branch to release/1.8.0 so it gets picked up in our upcoming release

**Comment by brettstack** [comment]
I think this is the first PR to receive 3 approvals (and so quickly!). #itsthesimplethings

**Comment by adamchainz** [comment]
I signed up for hacktoberfest but opening a PR counts rather than merges

**Comment by adamchainz** [comment]
Also as AWS employees should you really promote a Microsoft + DigitalOcean collaboration?

**Comment by keetonian** [comment]
There's free swag involved and they gave it a cool name, so why not? I'll go ahead and merge this in, thanks again!

**Pull request merged**
