### PR TITLE
Fix Authorizer: NONE support with AWS_IAM authorizer

### PR DESCRIPTION
**Pull request by TDaglis**
*Issue #1014*

*Description of changes:*
Change the validation of `method_authorizer` to support the combination of `AWS_IAM` default authorizer and `NONE` method authorizer.

When using `AWS_IAM` permission, it is only specified in the `DefaultAuthorizer`.  [Reference](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api-auth-object). This is a special case which leads to the `api_authorizers` being empty and results to not being able to add
 ```
Auth:
  Authorizer: 'NONE'
```
to a specific function, in order to override the default authorizer and make the function public.

*Description of how you validated changes:*

*Checklist:*

- [x] Write/update tests
- [x] `make pr` passes
- [ ] Update documentation
- [x] Verify transformed template deploys and application functions as expected
- [ ] Add/update example to `examples/2016-10-31`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by praneetap** [comment]
Thanks for the PR! The Travis build is failing. Once those errors are fixed we will give this a deeper review.

**Comment by keetonian** [comment]
Ran tests locally and they all passed. Re-running travis.

**Comment by jhaenchen** [comment]
I need this fix folks, just checking in!

**Comment by praneetap** [comment]
Thank you for the contribution! Could you please add end to end tests (Input/Output) that verifies the fix? You can take a look at this [pr](https://github.com/awslabs/serverless-application-model/pull/1043/files) for guidance. Please make sure you follow the pr checklist.

**Comment by TDaglis** [comment]
I attempted to add an end to end test, but it appears that it has issues in Python2.7. I don't understand what the issue is exactly. Any direction on this would be helpful. I'll get back to it.

**Comment by TDaglis** [comment]
It appears my output files had issues with Python2.7. I fixed them and now the tests pass.

**Pull request merged**
