### PR TITLE
feat: add Tags support to Http Api

### PR DESCRIPTION
**Pull request by keetonian**
*Issue #, if available:*
N/A
*Description of changes:*
Add tags support to Serverless::HttpApi resources
*Description of how you validated changes:*
Deployed templates to CFN to verify tags work, show up in console.
*Checklist:*

- [x] Write/update tests
- [x] `make pr` passes
- [x] Update documentation
- [x] Verify transformed template deploys and application functions as expected
- [ ] Add/update example to `examples/2016-10-31`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by keetonian** [comment]
Tests to write:
- Overwriting tags existing in OpenApi document
- Test to hit new error case for invalid OpenApi when using Tags

I may also need to verify that `tags` in the OpenApi document is a list before I assume it is one.

**Comment by alexw91** [comment]
# [Codecov](https://codecov.io/gh/awslabs/serverless-application-model/pull/1459?src=pr&el=h1) Report
> Merging [#1459](https://codecov.io/gh/awslabs/serverless-application-model/pull/1459?src=pr&el=desc) into [develop](https://codecov.io/gh/awslabs/serverless-application-model/commit/77fa3b9b027743b2aba62553640496f6231e1cc5&el=desc) will **decrease** coverage by `0.05%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/awslabs/serverless-application-model/pull/1459?src=pr&el=tree)

```diff
@@             Coverage Diff             @@
##           develop    #1459      +/-   ##
===========================================
- Coverage    94.36%   94.30%   -0.06%     
===========================================
  Files           78       78              
  Lines         4685     4709      +24     
  Branches       937      944       +7     
===========================================
+ Hits          4421     4441      +20     
- Misses         121      123       +2     
- Partials       143      145       +2     
```



------

[Continue to review full report at Codecov](https://codecov.io/gh/awslabs/serverless-application-model/pull/1459?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/awslabs/serverless-application-model/pull/1459?src=pr&el=footer). Last update [77fa3b9...317194b](https://codecov.io/gh/awslabs/serverless-application-model/pull/1459?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by alexw91** [comment]
# [Codecov](https://codecov.io/gh/awslabs/serverless-application-model/pull/1459?src=pr&el=h1) Report
> Merging [#1459](https://codecov.io/gh/awslabs/serverless-application-model/pull/1459?src=pr&el=desc) into [develop](https://codecov.io/gh/awslabs/serverless-application-model/commit/77fa3b9b027743b2aba62553640496f6231e1cc5&el=desc) will **decrease** coverage by `0.03%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/awslabs/serverless-application-model/pull/1459?src=pr&el=tree)

```diff
@@             Coverage Diff             @@
##           develop    #1459      +/-   ##
===========================================
- Coverage    94.36%   94.32%   -0.04%     
===========================================
  Files           78       78              
  Lines         4685     4655      -30     
  Branches       937      944       +7     
===========================================
- Hits          4421     4391      -30     
  Misses         121      121              
  Partials       143      143              
```


| [Impacted Files](https://codecov.io/gh/awslabs/serverless-application-model/pull/1459?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [samtranslator/plugins/exceptions.py](https://codecov.io/gh/awslabs/serverless-application-model/pull/1459/diff?src=pr&el=tree#diff-c2FtdHJhbnNsYXRvci9wbHVnaW5zL2V4Y2VwdGlvbnMucHk=) | `83.33% <0.00%> (-2.39%)` | :arrow_down: |
| [samtranslator/model/iam.py](https://codecov.io/gh/awslabs/serverless-application-model/pull/1459/diff?src=pr&el=tree#diff-c2FtdHJhbnNsYXRvci9tb2RlbC9pYW0ucHk=) | `92.85% <0.00%> (-1.43%)` | :arrow_down: |
| [samtranslator/translator/arn\_generator.py](https://codecov.io/gh/awslabs/serverless-application-model/pull/1459/diff?src=pr&el=tree#diff-c2FtdHJhbnNsYXRvci90cmFuc2xhdG9yL2Fybl9nZW5lcmF0b3IucHk=) | `86.95% <0.00%> (-0.55%)` | :arrow_down: |
| [samtranslator/model/sqs.py](https://codecov.io/gh/awslabs/serverless-application-model/pull/1459/diff?src=pr&el=tree#diff-c2FtdHJhbnNsYXRvci9tb2RlbC9zcXMucHk=) | `93.33% <0.00%> (-0.42%)` | :arrow_down: |
| [samtranslator/validator/validator.py](https://codecov.io/gh/awslabs/serverless-application-model/pull/1459/diff?src=pr&el=tree#diff-c2FtdHJhbnNsYXRvci92YWxpZGF0b3IvdmFsaWRhdG9yLnB5) | `95.23% <0.00%> (-0.42%)` | :arrow_down: |
| [samtranslator/open\_api/open\_api.py](https://codecov.io/gh/awslabs/serverless-application-model/pull/1459/diff?src=pr&el=tree#diff-c2FtdHJhbnNsYXRvci9vcGVuX2FwaS9vcGVuX2FwaS5weQ==) | `93.61% <0.00%> (+0.10%)` | :arrow_up: |
| [samtranslator/swagger/swagger.py](https://codecov.io/gh/awslabs/serverless-application-model/pull/1459/diff?src=pr&el=tree#diff-c2FtdHJhbnNsYXRvci9zd2FnZ2VyL3N3YWdnZXIucHk=) | `92.30% <0.00%> (-0.14%)` | :arrow_down: |
| [samtranslator/model/\_\_init\_\_.py](https://codecov.io/gh/awslabs/serverless-application-model/pull/1459/diff?src=pr&el=tree#diff-c2FtdHJhbnNsYXRvci9tb2RlbC9fX2luaXRfXy5weQ==) | `98.11% <0.00%> (-0.04%)` | :arrow_down: |
| [samtranslator/plugins/globals/globals.py](https://codecov.io/gh/awslabs/serverless-application-model/pull/1459/diff?src=pr&el=tree#diff-c2FtdHJhbnNsYXRvci9wbHVnaW5zL2dsb2JhbHMvZ2xvYmFscy5weQ==) | `99.02% <0.00%> (-0.03%)` | :arrow_down: |
| [samtranslator/model/sam\_resources.py](https://codecov.io/gh/awslabs/serverless-application-model/pull/1459/diff?src=pr&el=tree#diff-c2FtdHJhbnNsYXRvci9tb2RlbC9zYW1fcmVzb3VyY2VzLnB5) | `94.05% <0.00%> (-0.02%)` | :arrow_down: |
| ... and [8 more](https://codecov.io/gh/awslabs/serverless-application-model/pull/1459/diff?src=pr&el=tree-more) | |

------

[Continue to review full report at Codecov](https://codecov.io/gh/awslabs/serverless-application-model/pull/1459?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/awslabs/serverless-application-model/pull/1459?src=pr&el=footer). Last update [77fa3b9...4a6e671](https://codecov.io/gh/awslabs/serverless-application-model/pull/1459?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by alexw91** [comment]
# [Codecov](https://codecov.io/gh/awslabs/serverless-application-model/pull/1459?src=pr&el=h1) Report
> Merging [#1459](https://codecov.io/gh/awslabs/serverless-application-model/pull/1459?src=pr&el=desc) into [develop](https://codecov.io/gh/awslabs/serverless-application-model/commit/77fa3b9b027743b2aba62553640496f6231e1cc5&el=desc) will **decrease** coverage by `0.03%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/awslabs/serverless-application-model/pull/1459?src=pr&el=tree)

```diff
@@             Coverage Diff             @@
##           develop    #1459      +/-   ##
===========================================
- Coverage    94.36%   94.32%   -0.04%     
===========================================
  Files           78       78              
  Lines         4685     4655      -30     
  Branches       937      944       +7     
===========================================
- Hits          4421     4391      -30     
  Misses         121      121              
  Partials       143      143              
```


| [Impacted Files](https://codecov.io/gh/awslabs/serverless-application-model/pull/1459?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [samtranslator/plugins/exceptions.py](https://codecov.io/gh/awslabs/serverless-application-model/pull/1459/diff?src=pr&el=tree#diff-c2FtdHJhbnNsYXRvci9wbHVnaW5zL2V4Y2VwdGlvbnMucHk=) | `83.33% <0.00%> (-2.39%)` | :arrow_down: |
| [samtranslator/model/iam.py](https://codecov.io/gh/awslabs/serverless-application-model/pull/1459/diff?src=pr&el=tree#diff-c2FtdHJhbnNsYXRvci9tb2RlbC9pYW0ucHk=) | `92.85% <0.00%> (-1.43%)` | :arrow_down: |
| [samtranslator/translator/arn\_generator.py](https://codecov.io/gh/awslabs/serverless-application-model/pull/1459/diff?src=pr&el=tree#diff-c2FtdHJhbnNsYXRvci90cmFuc2xhdG9yL2Fybl9nZW5lcmF0b3IucHk=) | `86.95% <0.00%> (-0.55%)` | :arrow_down: |
| [samtranslator/model/sqs.py](https://codecov.io/gh/awslabs/serverless-application-model/pull/1459/diff?src=pr&el=tree#diff-c2FtdHJhbnNsYXRvci9tb2RlbC9zcXMucHk=) | `93.33% <0.00%> (-0.42%)` | :arrow_down: |
| [samtranslator/validator/validator.py](https://codecov.io/gh/awslabs/serverless-application-model/pull/1459/diff?src=pr&el=tree#diff-c2FtdHJhbnNsYXRvci92YWxpZGF0b3IvdmFsaWRhdG9yLnB5) | `95.23% <0.00%> (-0.42%)` | :arrow_down: |
| [samtranslator/open\_api/open\_api.py](https://codecov.io/gh/awslabs/serverless-application-model/pull/1459/diff?src=pr&el=tree#diff-c2FtdHJhbnNsYXRvci9vcGVuX2FwaS9vcGVuX2FwaS5weQ==) | `93.61% <0.00%> (+0.10%)` | :arrow_up: |
| [samtranslator/swagger/swagger.py](https://codecov.io/gh/awslabs/serverless-application-model/pull/1459/diff?src=pr&el=tree#diff-c2FtdHJhbnNsYXRvci9zd2FnZ2VyL3N3YWdnZXIucHk=) | `92.30% <0.00%> (-0.14%)` | :arrow_down: |
| [samtranslator/model/\_\_init\_\_.py](https://codecov.io/gh/awslabs/serverless-application-model/pull/1459/diff?src=pr&el=tree#diff-c2FtdHJhbnNsYXRvci9tb2RlbC9fX2luaXRfXy5weQ==) | `98.11% <0.00%> (-0.04%)` | :arrow_down: |
| [samtranslator/plugins/globals/globals.py](https://codecov.io/gh/awslabs/serverless-application-model/pull/1459/diff?src=pr&el=tree#diff-c2FtdHJhbnNsYXRvci9wbHVnaW5zL2dsb2JhbHMvZ2xvYmFscy5weQ==) | `99.02% <0.00%> (-0.03%)` | :arrow_down: |
| [samtranslator/model/sam\_resources.py](https://codecov.io/gh/awslabs/serverless-application-model/pull/1459/diff?src=pr&el=tree#diff-c2FtdHJhbnNsYXRvci9tb2RlbC9zYW1fcmVzb3VyY2VzLnB5) | `94.05% <0.00%> (-0.02%)` | :arrow_down: |
| ... and [8 more](https://codecov.io/gh/awslabs/serverless-application-model/pull/1459/diff?src=pr&el=tree-more) | |

------

[Continue to review full report at Codecov](https://codecov.io/gh/awslabs/serverless-application-model/pull/1459?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/awslabs/serverless-application-model/pull/1459?src=pr&el=footer). Last update [77fa3b9...4eeb285](https://codecov.io/gh/awslabs/serverless-application-model/pull/1459?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Pull request merged**
