### PR TITLE
added s3:DeleteObject to S3CrudPolicy

### PR DESCRIPTION
**Pull request by bmalnad**
*Issue #294 *

*Description of changes:*
Added s3:DeleteObject to S3CrudPolicy.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by brettstack** [comment]
Thanks! Could you please update the description and fix the failing tests (should just require adding this same line to the relevant test files)

**Comment by bmalnad** [comment]
Sorry about that.  This should be working now.  Tests completed locally...

**Comment by brettstack** [comment]
Raised this with @salmanap; he says it's okay since this is called CRUD and is resource scoped.

**Comment by brettstack** [comment]
Diff is all messed up due to the merge from master. I merged master into develop. Better diff available here https://github.com/awslabs/serverless-application-model/compare/develop...bmalnad:add-DeleteObject-to-S3CrudPolicy

**Comment by bmalnad** [comment]
Ugh.  Sorry

**Comment by brettstack** [comment]
Nope. My bad for not doing this in the first place.

**Comment by DanielLaberge** [comment]
When can this be expected in a release?

**Comment by keetonian** [comment]
@DanielLaberge This feature has been released and is now available

**Pull request merged**
