### PR TITLE
add support for Logs in AWS::Serverless::Function to control log group

### PR DESCRIPTION
**Pull request by tylersouthwick**
*Issue #, if available:*
#257

*Description of changes:*
Adds support for LogGroup definitions for AWS::Serverless::Function

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by Nr18** [comment]
Awesome @tylersouthwick will look at it in detail later.

**Comment by Tanoemon** [comment]
Have this feature really released?
https://github.com/awslabs/serverless-application-model/releases

**Comment by Nr18** [comment]
LGTM, but i'm not a SAM expert or a Expert Python developer (yet)

@Tanoemon it's not merged yet, if it's in develop it will be released in the next version if it's in master it's released and you can use it.

**Comment by Tanoemon** [comment]
@Nr18 Thank you for your reply.
Is "CloudWatch Logs Trigger" feature in this release https://github.com/awslabs/serverless-application-model/releases/tag/1.5 is different from this issue?

**Comment by Nr18** [comment]
Yes it's a different issue the one you refer to is execute a lambda based on a filter applied on a specified log group, this issue is about the output logs of the actual lambda function executions being stored for x amount of days instead of till the end of days.

**Comment by Tanoemon** [comment]
@Nr18  uh ! Thank you for your time.

**Comment by jacknagz** [comment]
Any update on this feature? Would really love to have this

**Comment by brettstack** [comment]
Thanks @tylersouthwick. I've approved this and will get someone else to provide second approval.

**Comment by ShaunEgan** [comment]
Would these configuration options be available in the `Globals` -> `Function` section as well? It would be nice to have the option to configure this once for all functions.

**Comment by johnc44** [comment]
Is there any reason why this hasn't been merged in yet?  Would really appreciate this feature!

**Comment by jfuss** [comment]
Looking through the attached Github issue: https://github.com/awslabs/serverless-application-model/issues/257#issuecomment-461896365 It seems like this was closed as something SAM cannot do without breaking customers.

**Pull request closed without merging**
