### PR TITLE
feat(policy-templates): add DynamoDBWritePolicy and S3WritePolicy

### PR DESCRIPTION
**Pull request by nmoutschen**
*Issue #, if available:*

*Description of changes:*

Added a policy template _DynamoDBWritePolicy_ that grants write-only access to a DynamoDB table. It grants the following permissions:

* "dynamodb:PutItem"
* "dynamodb:UpdateItem"
* "dynamodb:BatchWriteItem"

Added a policy template _S3WritePolicy_ that grants write-only access to an S3 bucket. It grants the following permissions:

* "s3:PutObject"
* "s3:PutObjectAcl"
* "s3:PutLifecycleConfiguration"

These two policy templates will help in case such as functions triggered by POST or PUT requests from an API Gateway.

*Description of how you validated changes:*

I ran `make pr`.

*Checklist:*

- [x] Write/update tests
- [x] `make pr` passes
- [ ] Update documentation _(no changes needed)_
- [x] Verify transformed template deploys and application functions as expected
- [x] Add/update example to `examples/2016-10-31`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by timoschilling** [comment]
I would like to have a `WritePolicy` without `DeleteObject`. What's your use case for a policy which allows the deletion but not the read of an object?

**Comment by nmoutschen** [comment]
That makes lots of sense. I removed `dynamodb:DeleteItem` and `s3:DeleteObject` from their respective policies.

I think a `DynamoDBDeletePolicy` or `S3DeletePolicy` might be too small in scope (since it's a single permission).

**Comment by timoschilling** [comment]
Why not the delete policies, it's still short and the style would be the same in the template.

**Comment by ShreyaGangishetty** [comment]
@nmoutschen Thank you for your contribution!
Could you please resolve merge conflicts for this PR?

**Comment by nmoutschen** [comment]
Not sure what's going on for the Python2.7 tests.

It's [failing to import enum](https://travis-ci.org/awslabs/serverless-application-model/jobs/653764819#L504), but the [enum34 module is installed](https://travis-ci.org/awslabs/serverless-application-model/jobs/653764819#L403). This also affects files that are not touched by this PR...

**Comment by alexw91** [comment]
# [Codecov](https://codecov.io/gh/awslabs/serverless-application-model/pull/1374?src=pr&el=h1) Report
> Merging [#1374](https://codecov.io/gh/awslabs/serverless-application-model/pull/1374?src=pr&el=desc) into [develop](https://codecov.io/gh/awslabs/serverless-application-model/commit/a1d7e546b44616ae34b205b759cde299bd723162&el=desc) will **increase** coverage by `0.52%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/awslabs/serverless-application-model/pull/1374?src=pr&el=tree)

```diff
@@             Coverage Diff             @@
##           develop    #1374      +/-   ##
===========================================
+ Coverage    94.39%   94.92%   +0.52%     
===========================================
  Files           78       78              
  Lines         4709     5555     +846     
  Branches       944     1232     +288     
===========================================
+ Hits          4445     5273     +828     
- Misses         121      134      +13     
- Partials       143      148       +5     
```


| [Impacted Files](https://codecov.io/gh/awslabs/serverless-application-model/pull/1374?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [samtranslator/model/api/http\_api\_generator.py](https://codecov.io/gh/awslabs/serverless-application-model/pull/1374/diff?src=pr&el=tree#diff-c2FtdHJhbnNsYXRvci9tb2RlbC9hcGkvaHR0cF9hcGlfZ2VuZXJhdG9yLnB5) | `95.68% <0.00%> (-2.64%)` | :arrow_down: |
| [samtranslator/plugins/globals/globals.py](https://codecov.io/gh/awslabs/serverless-application-model/pull/1374/diff?src=pr&el=tree#diff-c2FtdHJhbnNsYXRvci9wbHVnaW5zL2dsb2JhbHMvZ2xvYmFscy5weQ==) | `98.86% <0.00%> (-0.20%)` | :arrow_down: |
| [samtranslator/model/api/api\_generator.py](https://codecov.io/gh/awslabs/serverless-application-model/pull/1374/diff?src=pr&el=tree#diff-c2FtdHJhbnNsYXRvci9tb2RlbC9hcGkvYXBpX2dlbmVyYXRvci5weQ==) | `95.20% <0.00%> (+0.15%)` | :arrow_up: |
| [samtranslator/model/eventsources/push.py](https://codecov.io/gh/awslabs/serverless-application-model/pull/1374/diff?src=pr&el=tree#diff-c2FtdHJhbnNsYXRvci9tb2RlbC9ldmVudHNvdXJjZXMvcHVzaC5weQ==) | `92.00% <0.00%> (+1.24%)` | :arrow_up: |
| [samtranslator/model/sam\_resources.py](https://codecov.io/gh/awslabs/serverless-application-model/pull/1374/diff?src=pr&el=tree#diff-c2FtdHJhbnNsYXRvci9tb2RlbC9zYW1fcmVzb3VyY2VzLnB5) | `95.96% <0.00%> (+1.89%)` | :arrow_up: |
| [samtranslator/model/apigatewayv2.py](https://codecov.io/gh/awslabs/serverless-application-model/pull/1374/diff?src=pr&el=tree#diff-c2FtdHJhbnNsYXRvci9tb2RlbC9hcGlnYXRld2F5djIucHk=) | `96.00% <0.00%> (+2.25%)` | :arrow_up: |
| [samtranslator/open\_api/open\_api.py](https://codecov.io/gh/awslabs/serverless-application-model/pull/1374/diff?src=pr&el=tree#diff-c2FtdHJhbnNsYXRvci9vcGVuX2FwaS9vcGVuX2FwaS5weQ==) | `96.33% <0.00%> (+2.45%)` | :arrow_up: |

------

[Continue to review full report at Codecov](https://codecov.io/gh/awslabs/serverless-application-model/pull/1374?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/awslabs/serverless-application-model/pull/1374?src=pr&el=footer). Last update [a1d7e54...5b76fb0](https://codecov.io/gh/awslabs/serverless-application-model/pull/1374?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Pull request merged**
