### PR TITLE
feat(policy-template): adding cloudwatch:describeAlarmHistory policy …

### PR DESCRIPTION
**Pull request by ShreyaGangishetty**
…(#1264)

*Issue #, if available:*
Merged #1264 into master instead of develop.

*Description of changes:*
This PR is to merge #1264 into develop and I will submit another PR to revert #1264 from master

*Description of how you validated changes:*

*Checklist:*

- [ ] Write/update tests
- [ ] `make pr` passes
- [ ] Update documentation
- [ ] Verify transformed template deploys and application functions as expected
- [ ] Add/update example to `examples/2016-10-31`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by keetonian** [comment]
Note: requires a **merge** commit rather than a squash+merge.

**Comment by keetonian** [comment]
Can you fix the failing tests? Looks like there are some policy template differences you need to pick up on develop.

**Comment by ShreyaGangishetty** [comment]
@keetonian I will check and fix failing tests. Thank you

**Comment by ShreyaGangishetty** [comment]
@keetonian Please review #1306 . Closing this in favor of #1306

**Pull request closed without merging**
