### PR TITLE
feat: Add additional properties for Cloudwatch Schedule - Enabled, Name, Description

### PR DESCRIPTION
**Pull request by sambattalio**
*Issue #, if available:*
#934 
*Description of changes:*
Added the ability to set the name, description, and enable state of Cloudwatch Schedules.

Example usage of new properties:
```
Type: Schedule
Properties:
    Schedule: 'rate(1 minute)'
    Name: test-schedule
    Description: test schedule
    Enabled: True
```

*Description of how you validated changes:*
Validated changes through testing transforms as described in the contributing guidelines
and by verifying with an appended test case.

*Checklist:*

- [x] Write/update tests
- [x] `make pr` passes
- [x] Update documentation
- [x] Verify transformed template deploys and application functions as expected
- [x] Add/update example to `examples/2016-10-31`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by sambattalio** [comment]
Wondering if someone can help me figure out why the travis-ci build is failing. It seems like the 4 tests that are failing have been failing from the time I forked the repo.

**Comment by yan12125** [comment]
From the error message:

> Unknown exception while processing rule E3002: 'AWS::Cognito::UserPool.Policies'

I guess it's related to a cfn-lint issue: https://github.com/aws-cloudformation/cfn-python-lint/issues/1002.

**Comment by sambattalio** [comment]
> From the error message:
> 
> > Unknown exception while processing rule E3002: 'AWS::Cognito::UserPool.Policies'
> 
> I guess it's related to a cfn-lint issue: [aws-cloudformation/cfn-python-lint#1002](https://github.com/aws-cloudformation/cfn-python-lint/issues/1002).

@yan12125 that looked to be exactly the case. After triggering a rebuild on travis-ci after cfn-lint 22.2 released all the tests are passing! Thanks for the heads up on that issue. 👍

**Comment by brettstack** [comment]
Thanks for the contribution! Could you add a test for this?

**Comment by sambattalio** [comment]
Added an additional test for the schedule properties. Let me know if there is anything else I can do/fix for this!

**Comment by dvorontsov** [comment]
"Enabled: True"

Why capital "T", when other event types are "Enabled: true"?

**Pull request merged**
