### PR TITLE
Add FilterLogEventsPolicy to policy templates.

### PR DESCRIPTION
**Pull request by jbasden**
This commit adds a new policy to the policy templates
that grants permission to call the filter-log-events API,
given a Log Group.

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by brettstack** [comment]
@jbasden @ylynn is there a reason this has a trailing '*' in the permission?

**Comment by ylynn** [comment]
We manually tested the policy on IAM console, and only the one with a trailing '*' worked. From the doc https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazoncloudwatchlogs.html, '*' is needed.

**Comment by keetonian** [comment]
The documentation is a little ambiguous, but "Resource Types (*required)" seems to mean to me that the "*" is required if it is included there.

**Comment by ylynn** [comment]
@brettstack In the metric publisher app template, we export the arn of the logGroup, it is like `arn:aws:logs:us-west-2:411040894730:log-group:aws-serverless-repository-metric-publisher-app-MetricsLogGroup-EYGY4I68ZWCW:*`. The arn has * at the end. So when I create the policy, it is like `{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "logs:FilterLogEvents",
            "Resource": "arn:aws:logs:us-west-2:411040894730:log-group:aws-serverless-repository-metric-publisher-app-MetricsLogGroup-EYGY4I68ZWCW:*"
        }
    ]
}`.  I tried to remove *, use `arn:aws:logs:us-west-2:411040894730:log-group:aws-serverless-repository-metric-publisher-app-MetricsLogGroup-EYGY4I68ZWCW:`, and it did not work. I tried to remove ":" and keep *, use `arn:aws:logs:us-west-2:411040894730:log-group:aws-serverless-repository-metric-publisher-app-MetricsLogGroup-EYGY4I68ZWCW*`, and it worked.

**Pull request closed without merging**
