### PR TITLE
Added two templates to policy templates. Both are read only API calls…

### PR DESCRIPTION
**Pull request by davfaulk**
… (ce:* and Organizations:ListAccounts), that cannot be resource scoped, useful for using lambda for cost reporting. Also added SendRawEmail to existing SESCrudPolicy

*Issue #, if available:*

*Description of changes:*
Two new read-only policy templates to support adding https://github.com/aws-samples/aws-cost-explorer-report to the Serverless Application Repository. API calls do not support resource downscoping due to nature of calls.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by brettstack** [comment]
@davfaulk did you want to fix this?

**Comment by davfaulk** [comment]
Apologies for the delay - been traveling etc. Modified the other files, and ran tests.

**Comment by jlhood** [comment]
Sorry for the delayed response on this. We have since removed the redundant `docs/policy_templates_data/policy_templates.json` file so now the only file to modify is `samtranslator/policy_templates_data/policy_templates.json` Can you merge the latest develop branch, resolve conflicts and update this PR?

**Comment by brettstack** [comment]
Thanks @davfaulk, could you rebase this on latest develop branch? As James mentioned, we removed redundant file which is the main cause for this conflict.

**Comment by davfaulk** [comment]
Rebased off of current develop

**Pull request merged**
