### PR TITLE
add support for InlineCode in AWS::Serverless::Function

### PR DESCRIPTION
**Pull request by tylersouthwick**
*Issue #, if available:*
#287 

*Description of changes:*
Adds support for ZipFile lambda definitions

Due to the nature of 'allOf', the schema cannot enforce 'additionalProperties: false' with the current schema approach.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by brettstack** [comment]
Thanks @tylersouthwick. What's the benefit of this over letting SAM just zip the directory for you? I'm not strongly opposed to this, but want to understand customer value/frustration first before adding complexity.

**Comment by tylersouthwick** [comment]
Letting SAM zip the directory requires an s3 bucket to be setup and using the cloudformation cli. The specific use case where I use ZipFile is for really small lambdas such as cloudformation custom resources. I've also used it for small lambdas needed in step function workflows.

**Comment by parsnips** [comment]
I'd like to see this merged as well.  Makes inlined lambda's even shorter.

**Comment by brettstack** [comment]
Can you rename to InlineCode? ZipFile is confusing (I know it's what CloudFormation calls it).

**Comment by tylersouthwick** [comment]
@brettstack I agree that ZipFile was super confusing (when I first saw it I was wondering if it needed to be a base64 encoded zip file). I've updated it to be InlineCode

**Comment by teknogeek0** [comment]
+1 on this. Would for example streamline CFN Custom Resources a bit

**Comment by timoschilling** [comment]
when will this be released?

**Comment by Kharkovlanok** [comment]
Hi, although the commit has been merged, it seems the support in CF isn't effective yet, option InlineCode isn't recognized.

image

**Comment by timoschilling** [comment]
@Kharkovlanok It's only merged in develop not in master

**Comment by cdugga** [comment]
Great, thank you!

**Pull request merged**
