### PR TITLE
Update inbound-ses-spam-filter to include Fn ARN

### PR DESCRIPTION
**Pull request by dballance**
*Issue #, if available:* N/A

*Description of changes:* Currently, this filter is pretty useless to deploy as a nested stack. I cannot use the [published resource](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:077246666028:applications~inbound-ses-spam-filter) because I cannot tie the Function ARN to my SES ReceiptRuleAction. This change adds an output so that this template is useful for nested deployments.

*Description of how you validated changes:* No validation

*Checklist:*

- [x] Write/update tests
- [x] `make pr` passes
- [x] Update documentation
- [ ] Verify transformed template deploys and application functions as expected
- [ ] Add/update example to `examples/2016-10-31`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ShreyaGangishetty** [comment]
@dballance Could you please fix the merge conflicts and resubmit this PR?

**Comment by dballance** [comment]
I may just purge this PR and make the change on develop. I didn't make any of the changes except a single change to the template in this example.

**Comment by dballance** [comment]
Abandoning in favor of #1294

**Comment by ShreyaGangishetty** [comment]
@dballance Thank you. I will review #1294

**Pull request closed without merging**
