### PR TITLE
fix(LayerVersion): add UpdateReplacePolicy to LayerVersion resource

### PR DESCRIPTION
**Pull request by keetonian**
*Issue #, if available:*
https://github.com/awslabs/serverless-application-model/issues/703

*Description of changes:*
Add the `UpdateReplacePolicy` to LayerVersion resources so that old version aren't deleted.

*Description of how you validated changes:*
Deployed template with a layer to CFN, then updated the template to verify the old version doesn't get deleted.

*Checklist:*

- [x] Write/update tests
- [x] `make pr` passes
- [x] Update documentation

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by keetonian** [comment]
With the new `UpdateReplacePolicy`, changing the LayerVersion logical id is no longer necessary. However, if we were to remove this, it could trigger a new deployment of all current SAM layer version resources.

**Comment by brettstack** [comment]
This is changing existing functionality/tests. Any concerns with breaking existing users using this?

Will this force an update because we changed UpdateReplacePolicy?

**Comment by keetonian** [comment]
In testing, adding the `UpdateReplacePolicy` to the layer triggered a stack update but did not trigger an update on the LayerVersion resource.

**Comment by keetonian** [comment]
Update documentation: should use Lambda::LayerVersion resource and add the resource properties to it.

**Pull request closed without merging**
