### PR TITLE
Added RekognitionDetectOnlyPolicy to SAM

### PR DESCRIPTION
**Pull request by RobRoseKnows**
- To fix issue #245 and allow Detect* Rekognition permissions to be used
  without a collection ID.
- I'm not too familiar with this code base, so I based my changes on
  where RekognitionNoDataAccessPolicy appeared.
- So in the docs json, the samtranslator json and in the tests and examples
- If this passes all of Travis's tests, I'll come back and fix the
  examples.

*Issue #, if available:* #245 

*Description of changes:* Added a new policy template to allow for Rekognition DetectEtc calls without collection id.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by RobRoseKnows** [comment]
I believe that Travis Failure is fixed with #570. You'll need to merge it in first and then rebuild.

**Comment by brettstack** [comment]
Hi @RobRoseKnows thanks for this! Looks like you made the changes against the master branch  which has some conflicts with the develop branch. Could you checkout the develop branch and make the changes there? You'll notice that the policy templates json in `docs/` is gone and there's only a single place to update now (aside from tests).

**Comment by RobRoseKnows** [comment]
@brettstack Whoops, didn't see the `develop` branch existed. I've resolved the conflicts. Is there a public timeline as to when this is going to be deployed?

**Comment by RobRoseKnows** [comment]
Sorry for all the notifications, I had trouble with testing locally at first so I let Travis do it. Did get them passing now though.

**Comment by RobRoseKnows** [comment]
Is there a public timeline for when `develop` will be merged into `master`? I was hoping to use this policy for an entry in the [DevPost hackathon](https://serverlessrepo.devpost.com/) which currently ends October 2nd. Need to know if I need to find a work-around or not.

**Comment by jlhood** [comment]
We don't share exact dates for releases, but I can say that we're planning a release "soon." We're aware of the hackathon deadline, so we're planning upcoming releases accordingly. Thanks for participating in the hackathon! 😊

**Pull request merged**
